name: Sync 3x‑ui Upstream
on:
  schedule:
    - cron: '0 */6 * * *'  # UTC时间，每6小时自动同步一次
  workflow_dispatch: # 支持在Actions页面手动点击触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork from MHSanaei/3x-ui
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_repository: MHSanaei/3x-ui
          target_branch: main
          upstream_branch: main
          target_repository_token: ${{ secrets.GITHUB_TOKEN }}
